---
version: "2.1"
services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - /home/aorith/.config/docker_configs/calibre-web:/config
      - /media/datos/Syncthing/CalibreLibrary:/books
    ports:
      - 8083:8083
    restart: unless-stopped
