version: '3'
services:
  cardigann:
    container_name: cardigann
    image: linuxserver/cardigann
    ports:
      - "5060:5060/tcp"
    environment:
      TZ: Europe\Madrid
      UMASK_SET: 002
      PUID: 1000
      PGID: 1000
      HTTP_PROXY: torproxy:8118
    volumes:
       - /home/aorith/.config/docker_configs/cardigann:/config
    restart: "no"


  torproxy:
    container_name: torproxy
    image: aorith/torproxy
    ports:
      - "8118:8118"
      - "9050:9050"
      - "9051:9051"
    restart: "no"
    build:
      context: .
      dockerfile: torproxy
      args:
        b: 1500 # kb per sec


  jackett:
    container_name: jackett
    image: linuxserver/jackett
    depends_on:
      - torproxy
    ports:
        - "9117:9117/tcp"
    environment:
      TZ: Europe\Madrid
      UMASK_SET: 002
      PUID: 1000
      PGID: 1000
      RUN_OPTS: --ProxyConnection=torproxy:8118
    volumes:
       - /home/aorith/.config/docker_configs/jackett:/config
       - /media/datos/media/downloads:/downloads
       - /media/datos:/media/datos
    restart: "no"


  jenkins:
    container_name: jenkins
    image: nijlunsing/jenkins-armhf
    ports:
        - "8080:8080/tcp"
    environment:
      TZ: Europe\Madrid
      UMASK_SET: 002
      PUID: 1000
      PGID: 1000
    volumes:
       - /home/aorith/.config/docker_configs/jenkins:/var/jenkins_home
    restart: "no"


  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr
    ports:
        - "8686:8686/tcp"
    environment:
      TZ: Europe\Madrid
      UMASK_SET: 002
      PUID: 1000
      PGID: 1000
    volumes:
       - /home/aorith/.config/docker_configs/lidarr:/config
       - /media/datos/media/downloads/music:/downloads
       - /media/datos/Syncthing/Phone-Music:/music
       - /media/datos:/media/datos
    restart: "no"


  radarr:
    container_name: radarr
    image: linuxserver/radarr
    ports:
        - "7878:7878/tcp"
    environment:
      TZ: Europe\Madrid
      UMASK_SET: 002
      PUID: 1000
      PGID: 1000
    volumes:
       - /home/aorith/.config/docker_configs/radarr:/config
       - /media/datos/media/downloads/movies:/downloads
       - /media/datos/media/videos/movies:/movies
       - /media/datos:/media/datos
    restart: "no"


  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    ports:
        - "8989:8989/tcp"
    environment:
      TZ: Europe\Madrid
      UMASK_SET: 002
      PUID: 1000
      PGID: 1000
    volumes:
       - /home/aorith/.config/docker_configs/sonarr:/config
       - /media/datos/media/downloads/tv:/downloads
       - /media/datos/media/videos/tv:/tv
       - /media/datos:/media/datos
    restart: "no"


  jellyfin:
    container_name: jellyfin
    image: aorith/jellyfin
    ports:
        - "8096:8096/tcp"
        - "8920:8920/tcp"
    environment:
      TZ: Europe\Madrid
      UMASK_SET: 002
      PUID: 1000
      PGID: 1000
    volumes:
       - /home/aorith/.config/docker_configs/jellyfin:/config
       - /media/datos/media/downloads/tv:/downloads
       - /media/datos/media/videos/tv:/data/tvshows
       - /media/datos/media/videos/movies:/data/movies
       - /media/datos:/media/datos
    build:
        context: .
        dockerfile: jellyfin


  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - UMASK_SET=002 #optional
    volumes:
       - /home/aorith/.config/docker_configs/bazarr:/config
       - /media/datos/media/videos/movies:/movies
       - /media/datos/media/videos/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
