version: '3'
services:
  torproxy:
    container_name: torproxy
    image: aorith/torproxy
    ports:
      - "8118:8118"
      - "9050:9050"
      - "9051:9051"
    restart: unless-stopped
    build:
      context: .
      dockerfile: torproxy
      #args:
      #  b: 1500 # kb per sec

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    depends_on:
      - torproxy
    ports:
        - "9117:9117/tcp"
    environment:
      TZ: Europe\Madrid
      UMASK_SET: 002
      PUID: 9999
      PGID: 9999
      RUN_OPTS: --ProxyConnection=torproxy:8118
    volumes:
       - /DATA/docker_configs/jackett:/config
       - /MEDIA/downloads:/downloads
       - /MEDIA:/MEDIA
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    ports:
        - "7878:7878/tcp"
    environment:
      TZ: Europe\Madrid
      UMASK_SET: 002
      PUID: 9999
      PGID: 9999
    volumes:
       - /DATA/docker_configs/radarr:/config
       - /MEDIA/downloads/movies:/downloads
       - /MEDIA/videos/movies:/movies
       - /MEDIA:/MEDIA
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    ports:
        - "8989:8989/tcp"
    environment:
      TZ: Europe\Madrid
      UMASK_SET: 002
      PUID: 9999
      PGID: 9999
    volumes:
       - /DATA/docker_configs/sonarr:/config
       - /MEDIA/downloads/tv:/downloads
       - /MEDIA/videos/tv:/tv
       - /MEDIA:/MEDIA
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=9999
      - PGID=9999
      - TZ=Europe/Madrid
      - UMASK_SET=002 #optional
    volumes:
       - /DATA/docker_configs/bazarr:/config
       - /MEDIA/videos/movies:/movies
       - /MEDIA/videos/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  jellyfin:
    container_name: jellyfin
    image: linuxserver/jellyfin
    ports:
        - "8096:8096/tcp"
        - "8920:8920/tcp"
    environment:
      TZ: Europe\Madrid
      UMASK_SET: 002
      PUID: 9999
      PGID: 9999
    volumes:
       - /DATA/docker_configs/jellyfin:/config
       - /MEDIA/downloads/tv:/downloads
       - /MEDIA/videos/tv:/data/tvshows
       - /MEDIA/videos/movies:/data/movies
       - /MEDIA:/MEDIA
    restart: unless-stopped

  plex:
    container_name: plex
    image: linuxserver/plex
    ports:
        - "8096:8096/tcp"
        - "8920:8920/tcp"
    environment:
      TZ: Europe\Madrid
      UMASK_SET: 002
      PUID: 9999
      PGID: 9999
      VERSION: docker
    volumes:
       - /DATA/docker_configs/plex:/config
       - /MEDIA/videos/tv:/tv
       - /MEDIA/videos/movies:/movies
       - /MEDIA:/MEDIA
    restart: unless-stopped
